{% set on_win = SUBDIR in ('win-64', 'win-32') %}
{% set version = "4.13.0" %}
# Running pytest requires the inclusion of test files which baloons
# the size of the package; values can be "yes" or "no"
{% set run_pytest = "no" %}

package:
  name: conda
  version: {{ version }}

source:
  fn: conda-{{ version }}.tar.gz
  url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
  sha256: 30c4cee48ef3acc4e2d802c05baee44f5385f55b0c23c547b0961c51e1d140d2
  patches:
    - gh9946_utf_16_replacement.patch

build:
  number: 1
  # These are present when the new environment is created
  # so we have to exempt them from the list of initial files
  # for conda-build to realize they should be included.
  always_include_files:
    - bin/conda                    # [unix]
    - bin/activate                 # [unix]
    - bin/deactivate               # [unix]
    - Scripts/activate.bat         # [win]
    - Scripts/activate             # [win]
    - Scripts/deactivate           # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - m2-filesystem                # [win]
    - m2-bash                      # [win]
    - m2-base                      # [win]

  host:
    - python
    - conda-package-handling >=1.3.0
    - menuinst >=1.4.11,<2         # [win]
    - pip
    - ruamel_yaml >=0.11.14,<0.16
    - setuptools >=31.0.1
  run:
    - python
    - conda-package-handling >=1.3.0
    - menuinst >=1.4.11,<2         # [win]
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - requests >=2.18.4,<3
    - ruamel_yaml >=0.11.14,<0.16
    - setuptools >=31.0.1
  run_constrained:
    - conda-build >=3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
    - cytoolz >=0.8.1

test:
{% if run_pytest == 'yes' %}
  source_files:
    - tests
    - setup.cfg
{% endif %}
  requires:
    - mock
{% if run_pytest == 'yes' %}
    - pytest
{% endif %}
    - pexpect
    - responses
    - m2-filesystem  # [win]
    - m2-bash        # [win]
    - m2-base        # [win]
  imports:
    - conda
    - conda_env
  files:
    - test_runner.bat                # [win]
    - test_runner.sh                 # [unix]
    - commands_to_test.bat           # [win]
    - commands_to_test.sh            # [unix]
  downstreams:
    - conda-smithy  # [python_impl == "cpython"]
  commands:
    - env run_pytest={{ run_pytest }} bash test_runner.sh   # [unix]
    - set run_pytest={{ run_pytest }} && .\test_runner.bat  # [win]

about:
  home: https://conda.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package and environment manager.
  description: >
    Conda is an open source package management system and environment management system for installing multiple versions of software packages and their dependencies and switching easily between them. It works on Linux, OS X and Windows, and was created for Python programs but can package and distribute any software.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/conda

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - mbargull
    - jezdez
