{% set name = "conda" %}
{% set version = "4.2.3" %}
{% set checksum = "f90898c8e4a83615937d8df15640760fa0b230611f74b46fede58112e91b29b9" %}


package:
  name: conda
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  entry_points:
    - conda = conda.cli:main
  always_include_files:
    - bin/conda                            # [unix]
    - bin/activate                         # [unix]
    - bin/deactivate                       # [unix]
    - exec/conda                           # [unix]
    - exec/activate                        # [unix]
    - exec/deactivate                      # [unix]
    - etc/fish/conf.d/conda.fish           # [unix]
    - Scripts/activate.bat                 # [win]
    - Scripts/activate                     # [win]
    - Scripts/conda.exe                    # [win]
    - Scripts/conda-script.py              # [win]
    - Scripts/conda-script.pyc             # [win]
    - Scripts/deactivate.bat               # [win]
    - Scripts/deactivate                   # [win]
    - exec/activate.bat                    # [win]
    - exec/activate                        # [win]
    - exec/conda.exe                       # [win]
    - exec/conda-script.py                 # [win]
    - exec/conda-script.pyc                # [win]
    - exec/deactivate.bat                  # [win]
    - exec/deactivate                      # [win]
    - etc/fish/conf.d/conda.fish           # [win]

requirements:
  build:
    - python
    - setuptools
    - conda-env >=2.5
    - menuinst                  # [win]
    - pycosat
    - pyyaml
    - requests
    - ruamel_yaml

  run:
    - python
    - conda-env >=2.5
    - enum34                    # [py<34]
    - menuinst                  # [win]
    - pycosat
    - pyyaml
    - requests
    - ruamel_yaml

test:
  imports:
    - conda

  commands:
    - which conda                  # [unix]
    - where conda                  # [win]
    - conda --version
    - conda info

about:
  home: https://github.com/conda/conda
  summary: OS-agnostic, system-level binary package manager.
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - msarahan
    - pelson
