{% set version = "25.5.1" %}
{% set sha256 = "b3d91503d8f95f29bffd0d47c0f6f9aaa50443a250d5a201ba6866c79099a5c0" %}
# Running pytest requires the inclusion of test files which baloons
# the size of the package; values can be "yes" or "no"
{% set run_pytest = "no" %}

package:
  name: conda
  version: {{ version }}

source:
  url: https://github.com/conda/conda/releases/download/{{ version }}/conda-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  folder: conda-src

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install conda-src/ --no-deps --no-build-isolation -vv && {{ PYTHON }} -m conda init --install
  # These are present when the new environment is created
  # so we have to exempt them from the list of initial files
  # for conda-build to realize they should be included.
  always_include_files:
    - bin/conda                    # [unix]
    - bin/activate                 # [unix]
    - bin/deactivate               # [unix]
    - Scripts/activate.bat         # [win]
    - Scripts/activate             # [win]
    - Scripts/deactivate           # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - m2-filesystem                # [win]
    - m2-bash                      # [win]
    - m2-base                      # [win]
  host:
    - python {{ python_min }}      # [not python_ge_310]
    - python 3.10                  # [python_ge_310]
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
    # for `conda init` in build/script above
    - boltons >=23.0.0
    - frozendict >=2.4.2
    - menuinst >=2
    - platformdirs >=3.10.0
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - tqdm >=4
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=24.11.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0           # [python_ge_310]
    - zstandard >=0.19.0
    - python >=3.10                # [python_ge_310]
    - python <3.10                 # [not python_ge_310]
    - python >={{ python_min }}    # [not python_ge_310]
  run_constrained:
    - conda-build >=24.3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6

test:
{% if run_pytest == 'yes' %}
  source_files:
    - conda-src/tests
    - conda-src/setup.cfg
{% endif %}
  requires:
    - mock
{% if run_pytest == 'yes' %}
    - pytest
{% endif %}
    - pexpect
    - responses
    - m2-filesystem  # [win]
    - m2-bash        # [win]
    - m2-base        # [win]
    - python 3.11                # [python_ge_310]
    - python {{ python_min }}    # [not python_ge_310]
  imports:
    - conda
    - conda_env
  files:
    - test_runner.bat                # [win]
    - test_runner.sh                 # [unix]
    - commands_to_test.bat           # [win]
    - commands_to_test.sh            # [unix]
  downstreams:
    - conda-smithy  # [python_ge_310 and not osx]

about:
  home: https://conda.io
  license: BSD-3-Clause
  license_file: conda-src/LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
  description: |
    Conda is an open source package management system and environment
    management system for installing multiple versions of software packages
    and their dependencies and switching easily between them. It works on
    Linux, OS X and Windows, and was created for Python programs but can
    package and distribute any software.
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  dev_url: https://github.com/conda/conda

extra:
  recipe-maintainers:
    - dbast
    - isuruf
    - jakirkham
    - jezdez
    - kenodegard
    - mbargull
    - ocefpaf
    - beeankha
