travis:
  secure:
    BINSTAR_TOKEN: fLc/Km8qc7TwH6K6yG3tx4dAWrkJnQAdHQWLha+1nagydqKqTCbLLISSEctcS5lZac6055S+If7QudjWkwhKhj0q7KeUOeJF4MlE9UCDXtnL6W/vGu2q0I3ifCFzuBUaC0795cIDq5X4exW8usDRYTuL/GGx7BFTYT/Lrjg/FqbsWgvdN7hWOB58Ui4ZQxyTzF4hFQVZMOePxy+/pp8bv4eQi4UDS1jtDZmcR3leQGG5w6IyYoFuZQun5a/6pG39VyYVDuULtJZubM+MauEpydJEm2WrobsSeL5f5VUffvnEpWAftyuCr0rDpZ9BhTiT8gln4MhDVpQEKnL32riDRxwvLQB7ym3yPZMXE93+ey1+P43QWq1fnAMCx9lmWNzXEJSo5Jc/Hwud4nwIK1lTZduQngR6K4McpyVtLpf/e4P/Bhk5oifVfJV/wo6SgyJcVcD3njb543XdhO8JqbAYMqArKU/I8az/7DuijIObLssU4zfroGATsA9FaagiBq8TmxXxWHfin1WDgsznV9ubQK9aL2FX/mWE2XwLgypVmWbBjGP/QU4ANC8yEW6mcwYcV3sBN3rd+pWXY//w7O1cGxlC2So6yqh8eo4nJrkCzZEAkc5t6KluCuJQWpB7gQbSoj/U+2vwszFm9cSlaxGKP29YOaRKwQJF8BpeDYqc9vQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
